search_input_by_name = "q"
search_submit_btn = "//button[@type='submit']"
searched_product_text= "//span[@class='_10Ermr']/span[text()='%s']"
close_login_popup = "//button[text()='✕']"
max_price_drp = "//div[@class='_3uDYxP']/select"
result_text = "//span[@class='_10Ermr']"
products_list = "//div[contains(@data-id,'MOB')]"
add_cart = "//button[text()='Add to cart']"
cart_number = "//div[@class='KK-o3G']"